-- Pluggin Init
require('pluggins.manager')
require('pluggins.barbar')
require('pluggins.nvim-tree')
require('pluggins.galaxyline')
require('pluggins.which-key')
require('pluggins.telescope')
require('pluggins.gitsigns')
require('pluggins.toggleterm')
require('pluggins.autopairs')
require('pluggins.lsp')
require('pluggins.lspsaga')
require('pluggins.nvim-cmp')
require('pluggins.treesitter')
require('pluggins.nui-nvim')
require('pluggins.colorizer')

-- LSP
require('pluggins.lsp.angular-ls')
require('pluggins.lsp.bash-ls')
require('pluggins.lsp.css-ls')
require('pluggins.lsp.docker-ls')
require('pluggins.lsp.efm-ls')
require('pluggins.lsp.haskell-ls')
require('pluggins.lsp.html-ls')
require('pluggins.lsp.jdtls')
require('pluggins.lsp.json-ls')
require('pluggins.lsp.lua-ls')
require('pluggins.lsp.pyright-ls')
require('pluggins.lsp.tsserver-ls')
require('pluggins.lsp.vim-ls')
require('pluggins.lsp.yaml-ls')
