-- Pluggin Init
require('pluggins.manager')
require('pluggins.barbar')
require('pluggins.nvim-tree')
require('pluggins.galaxyline')
require('pluggins.which-key')
require('pluggins.telescope')
require('pluggins.gitsigns')
require('pluggins.toggleterm')
require('pluggins.autopairs')
require('pluggins.lsp')
require('pluggins.nvim-cmp')
require('pluggins.treesitter')
require('pluggins.nui-nvim')
require('pluggins.colorizer')
