-- Pluggin Init
require('pluggins.barbar')
require('pluggins.colorizer')
require('pluggins.compe')
require('pluggins.lsp')
require('pluggins.lspsaga')
require('pluggins.treesitter')
require('pluggins.galaxyline')
require('pluggins.telescope')
require('pluggins.nvim-tree')

-- LSP
require('pluggins.lsp.bash-ls')
require('pluggins.lsp.css-ls')
require('pluggins.lsp.docker-ls')
require('pluggins.lsp.haskell-ls')
require('pluggins.lsp.json-ls')
require('pluggins.lsp.lua-ls')
require('pluggins.lsp.pyright-ls')
require('pluggins.lsp.tsserver-ls')
require('pluggins.lsp.vim-ls')
require('pluggins.lsp.yaml-ls')
