-- Servers
require('pluggins.lsp.servers.angular-ls')
require('pluggins.lsp.servers.bash-ls')
require('pluggins.lsp.servers.css-ls')
require('pluggins.lsp.servers.docker-ls')
require('pluggins.lsp.servers.efm-ls')
require('pluggins.lsp.servers.haskell-ls')
require('pluggins.lsp.servers.html-ls')
require('pluggins.lsp.servers.jdtls')
require('pluggins.lsp.servers.json-ls')
require('pluggins.lsp.servers.lua-ls')
require('pluggins.lsp.servers.pyright-ls')
require('pluggins.lsp.servers.tsserver-ls')
require('pluggins.lsp.servers.vim-ls')
require('pluggins.lsp.servers.yaml-ls')
