-- Servers
require('plugins.lsp.servers.angular-ls')
require('plugins.lsp.servers.bash-ls')
require('plugins.lsp.servers.css-ls')
require('plugins.lsp.servers.null-ls')
require('plugins.lsp.servers.haskell-ls')
require('plugins.lsp.servers.html-ls')
require('plugins.lsp.servers.emmet-ls')
require('plugins.lsp.servers.json-ls')
require('plugins.lsp.servers.lua-ls')
require('plugins.lsp.servers.py-lsp')
require('plugins.lsp.servers.tsserver-ls')
require('plugins.lsp.servers.vim-ls')
require('plugins.lsp.servers.yaml-ls')
