-- Own version of kind
vim.lsp.protocol.CompletionItemKind = {
	" (text)",
	" (reference)",
	" (value)",
	" (snippet)",
	" (event)",
	" (field)",
	" (property)",
	" (function)",
	" (method)",
	" (file)",
	" (folder)",
	" (enum)",
	" (typeparameter)",
	" (constant)",
	" (variable)",
	" (keyword)",
	" (class)",
	" (unit)",
	" (module)",
	" (color)",
	"駱 (operator)",
	"壟(interface)",
	"襁 (constructor)",
	"ﱔ (enummember)",
	"ﴰ (struct)",
}
