-- Plugin Init
require('plugins.manager')
require('plugins.barbar')
require('plugins.nvim-tree')
-- require('plugins.galaxyline')
require('plugins.statusline.feline')
require('plugins.which-key')
require('plugins.telescope')
require('plugins.gitsigns')
require('plugins.toggleterm')
require('plugins.autopairs')
require('plugins.lsp')
require('plugins.nvim-cmp')
require('plugins.treesitter')
require('plugins.nui-nvim')
require('plugins.colorizer')
