-- Plugin Init
require('plugins.manager')
require('plugins.lsp')
require('plugins.treesitter')
require('plugins.telescope')
require('plugins.completion')
require('plugins.ef')
require('plugins.keys')
require('plugins.ui-components')
require('plugins.gitsigns')
require('plugins.colors')
